# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.1'
target 'XBADBaseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FBAudienceNetwork', '~> 5.7.0'
  pod 'ObjectMapper'
  pod 'Alamofire', '~> 4.9.1'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'SDWebImage/WebP'
  pod 'SDWebImage/GIF'
  
  pod 'Google-Mobile-Ads-SDK', '7.48.0'
  
  # Mintegral广告
  pod 'MintegralAdSDK/NativeAd', '5.8.8.0'
  pod 'MintegralAdSDK/RewardVideoAd', '5.8.8.0'
  pod 'MintegralAdSDK/InterstitialVideoAd', '5.8.8.0'
  
#  pod 'ZFPlayer', '3.2.13'
#  pod 'ZFPlayer/ControlView', '3.2.13'
#  pod 'ZFPlayer/AVPlayer', '3.2.13'
  
  pod 'AppLovinSDK', '6.11.1'
end
